name: triplo_ingles
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  aligned_tooltip: 0.0.1
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  chewie: ^1.12.1
  cloud_firestore: ^5.6.11
  cloud_firestore_platform_interface: ^6.6.11
  cloud_firestore_web: ^4.4.11
  cloud_functions: ^5.6.1
  cloud_functions_platform_interface: ^5.8.1
  cloud_functions_web: ^4.11.4
  collection: 1.19.1
  csslib: ^1.0.2
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: ^2.0.7
  file_picker: ^10.2.0
  firebase_analytics: ^11.5.2
  firebase_analytics_platform_interface: ^4.4.2
  firebase_analytics_web: ^0.5.10+15
  firebase_auth: ^5.6.2
  firebase_auth_platform_interface: ^7.7.2
  firebase_auth_web: ^5.15.2
  firebase_core: ^3.15.1
  firebase_core_platform_interface: ^6.0.0
  firebase_core_web: ^2.24.1
  firebase_performance: ^0.10.1+9
  firebase_performance_platform_interface: ^0.1.5+9
  firebase_performance_web: ^0.1.7+15
  firebase_storage: ^12.4.9
  firebase_storage_platform_interface: ^5.2.9
  firebase_storage_web: ^3.10.16
  fl_chart: ^1.0.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_plugin_android_lifecycle: ^2.0.28
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^10.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.0
  google_sign_in_android: ^7.0.1
  google_sign_in_ios: ^6.0.0
  google_sign_in_platform_interface: ^3.0.0
  google_sign_in_web: ^1.0.0
  html: ^0.15.6
  http: 1.2.2
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+23
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: ^0.2.1+2
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: 0.2.1+1
  intl: 0.20.2
  json_path: ^0.7.6
  mask_text_input_formatter: 2.9.0
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.17
  path_provider_foundation: ^2.4.1
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  platform_detect: ^2.1.5
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  provider: ^6.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  stream_transform: ^2.1.1
  table_calendar: ^3.2.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: ^2.4.1
  url_launcher_windows: ^3.1.4
  uuid: ^4.0.0
  video_player: ^2.10.0
  video_player_android: ^2.8.7
  video_player_avfoundation: ^2.7.2
  video_player_platform_interface: ^6.4.0
  video_player_web: ^2.3.5
  webview_flutter: 4.9.0
  webview_flutter_android: ^3.16.9
  webview_flutter_platform_interface: ^2.13.1
  webview_flutter_wkwebview: ^3.22.0
  webviewx_plus: ^0.5.1
  youtube_player_flutter: ^8.1.1
  youtube_player_iframe: ^5.2.0
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  pointer_interceptor: 0.10.1+2
  pointer_interceptor_ios: 0.10.1
  pointer_interceptor_platform_interface: 0.10.0+1
  pointer_interceptor_web: 0.10.2+1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  image: ^4.5.4
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
  fonts:
    - family: TriploWhite
      fonts:
        - asset: assets/fonts/TriploWhite.ttf
    - family: Carteira2
      fonts:
        - asset: assets/fonts/carteira2.ttf
    - family: Notify
      fonts:
        - asset: assets/fonts/notify.ttf
    - family: Calendar
      fonts:
        - asset: assets/fonts/calendar.ttf
    - family: DadosEndereco
      fonts:
        - asset: assets/fonts/dados_endereco.ttf
    - family: DadosSuporte
      fonts:
        - asset: assets/fonts/dados_suporte.ttf
    - family: DadosUser
      fonts:
        - asset: assets/fonts/dados_user.ttf
    - family: PlanoPrata
      fonts:
        - asset: assets/fonts/plano_prata.ttf
    - family: Planeta
      fonts:
        - asset: assets/fonts/planeta.ttf
    - family: Relogio
      fonts:
        - asset: assets/fonts/relogio.ttf
    - family: Zoom
      fonts:
        - asset: assets/fonts/zoom.ttf
    - family: Logo22223
      fonts:
        - asset: assets/fonts/logo22223.ttf
    - family: 33logo22223
      fonts:
        - asset: assets/fonts/33logo22223.ttf
    - family: 444triplo
      fonts:
        - asset: assets/fonts/444triplo.ttf
